# -*- coding: utf-8 -*-
# config.py

# full - Полное название для вкладок, short - Краткое название для шапки таблицы
FIELDS_CONFIG = {                                                                        # (0)
    "id"          : {"full": "№ п/п", "short": "№ п/п", "type": int, "pos_table": 1, "pos_vertical": 1, "width": 50},  # (4)
    "year"        : {"full": "Год", "short": "Год", "type": int, "pos_table": 2, "pos_vertical": 2, "width": 50},      # (4)
    "cruise_name" : {"full": "Название рейса", "short": "Рейс", "type": str, "pos_table": 3, "pos_vertical": 3, "width": 50},  # (4)
    "vessel"      : {"full": "Научно-исследовательское судно", "short": "Судно", "type": str, "pos_table": 4, "pos_vertical": 4, "width": 220},  # (4)
    "cruise_num"  : {"full": "Номер рейса", "short": "№ рейса", "type": int, "pos_table": 5, "pos_vertical": 5, "width": 50},  # (4)
    "chief_cruise" : {"full": "Начальник научного рейса", "short": "Нач.рейса", "type": str, "pos_table": 6, "pos_vertical": 6, "width": 100},  # (4)
    "date_start"  : {"full": "Дата начала рейса", "short": "Дата начала", "type": str, "pos_table": 7, "pos_vertical": 7, "width": 60},  # (4)
    "date_end"    : {"full": "Дата окончания рейса", "short": "Дата оконч.", "type": str, "pos_table": 8, "pos_vertical": 8, "width": 60},  # (4)
    "stage_num"   : {"full": "Номер этапа рейса", "short": "№ этапа", "type": int, "pos_table": 9, "pos_vertical": 9, "width": 50},  # (4)
    "chief_geophysics": {"full": "Начальник отряда геофизики", "short": "Нач.отр.геофизики", "type": str, "pos_table": 10, "pos_vertical": 10, "width": 100},  # (4)
    "chief_seismic" : {"full": "Начальник отряда сейсмических исследований", "short": "Нач.отр.сейсм.исследований", "type": str, "pos_table": 11, "pos_vertical": 11, "width": 100},  # (4)
    "initiator"   : {"full": "Инициатор научной задачи", "short": "Инициатор", "type": str, "pos_table": 12, "pos_vertical": 12, "width": 100},  # (4)
    "region"      : {"full": "Район проведения исследований", "short": "Район", "type": str, "pos_table": 13, "pos_vertical": 13, "width": 100},  # (4)
    "data_type"   : {"full": "Тип собранных данных", "short": "Тип данных", "type": str, "pos_table": 14, "pos_vertical": 14, "width": 100},  # (4)
    "device"      : {"full": "Используемый прибор", "short": "Прибор", "type": str, "pos_table": 15, "pos_vertical": 15, "width": 100},  # (4)
    "disk_num"    : {"full": "Порядковый номер диска", "short": "№ диска", "type": int, "pos_table": 16, "pos_vertical": 16, "width": 50},  # (4)
    "disk_inv_num" : {"full": "Инвентарный номер носителя", "short": "Инв.№ диска", "type": int, "pos_table": 17, "pos_vertical": 17, "width": 70},  # (4)
    "processing_stage": {"full": "степень обработки данных", "short": "Степень обработки", "type": str, "pos_table": 18, "pos_vertical": 18, "width": 100},  # (4)
    "file_format" : {"full": "Формат данных", "short": "Формат", "type": str, "pos_table": 19, "pos_vertical": 19, "width": 100},  # (4)
    "data_volume" : {"full": "Общий объем сохраненных данных", "short": "Объем данных", "type": str, "pos_table": 20, "pos_vertical": 20, "width": 70},  # (4)
}            # (0)

# Группировка латинских ключей строго по вашим 3 вкладкам
TABS_CONFIG = {                                                                          # (0)
    "Общая информация": [                                                                # (4)
        "id", "year",                                                                    # (8)
        "cruise_name", "vessel",                                                         # (8)
        "cruise_num", "chief_cruise",                                                    # (8)
        "date_start", "date_end"                                                         # (8)
    ],                                                                                   # (4)
    "Геофизика и приборы": [                                                             # (4)
        "stage_num", "chief_geophysics",                                                 # (8)
        "chief_seismic", "initiator",                                                    # (8)
        "region", "data_type",                                                           # (8)
        "device"                                                                         # (8)
    ],                                                                                   # (4)
    "Носители и файлы": [                                                                # (4)
        "disk_num", "disk_inv_num",                                                      # (8)
        "processing_stage", "file_format",                                               # (8)
        "data_volume"                                                                    # (8)
    ]                                                                                    # (4)
}                                                                                        # (0)

# Справочники для выпадающих списков привязаны строго к латинским именам переменных
DICTIONARIES = {                                                                         # (0)
    "vessel"          : ["Академик Николай Страхов", "Академик Борис Петров", "Академик Мстислав Келдыш", "Академик Иоффе", "Академик Сергей Вавилов", "Профессор Штокман"],  # (4)
    "chief_cruise"    : ["Дорохов Д.В.", "Кречик В.А.", "Крек А.В.", "Пономаренко Е.П.", "Бубнова Е.С.",  "Данченков А.Р.", "Дорохова Е.В.", "Фрей Дмитрий Ильич"],  # (4)
    "chief_geophysics": ["Дорохов Д.В.", "Ежов В.Е.", "Данченков А.Р.", "Дорохова Е.В.", "Дудков И.Ю.", "Кречик В.А.", "Пономаренко Е.П."],  # (4)
    "chief_seismic"   : ["Ежов В.Е.", "Ананьев Р.А."],  # (4)
    "initiator"       : ["Институт океанологии", "МГУ", "РАН"],  # (4)
    "region"          : ["Баренцево море", "SEB", "FZ", "Балтийское море", "Атлантика"],  # (4)
    "data_type"       : ["ОЛЭ", "МЛЭ", "Профилограф", "ГЛБО", "ADCP", "SADCP", "Сейсмокоса"],  # (4)
    "device"          : ["Konsberg EA-400", "EA-600", "SeaBat T50", "Parasound P70", "Parasound P35", "Benthos C3D", "SES2000"],  # (4)
    "processing_stage": ["Необработанные", "Обработанные", "Сырые и обработанные"],  # (4)
    "file_format"     : ["ASD, SEG-Y", "PDS2000", "ASCII", "DTM", "GeoTiff", "SEG-Y", "RAW", "SES2000"],  # (4)
}                                                                                        # (0)

