# -*- coding: utf-8 -*-
# config.py

FIELDS_CONFIG = {                                                                        # (0)
    "id": {"full": "№ п/п", "short": "№ п/п", "type": int, "pos_table": 1, "pos_vertical": 1},  # (4)
    "year": {"full": "Год", "short": "Год", "type": int, "pos_table": 2, "pos_vertical": 2},  # (4)
    "cruise_name": {"full": "Рейс", "short": "Рейс", "type": str, "pos_table": 3, "pos_vertical": 3},  # (4)
    "vessel": {"full": "Судно", "short": "Судно", "type": str, "pos_table": 4, "pos_vertical": 4},  # (4)
    "cruise_num": {"full": "№ рейса", "short": "№ рейса", "type": int, "pos_table": 5, "pos_vertical": 5},  # (4)
    "chief_cruise": {"full": "Начальник рейса", "short": "Нач. рейса", "type": str, "pos_table": 6, "pos_vertical": 6},  # (4)
    "date_start": {"full": "Дата начала рейса", "short": "Начало рейса", "type": str, "pos_table": 7, "pos_vertical": 7},  # (4)
    "date_end": {"full": "Дата окончания рейса", "short": "Конец рейса", "type": str, "pos_table": 8, "pos_vertical": 8},  # (4)
    "stage_num": {"full": "№ этапа рейса", "short": "№ этапа", "type": int, "pos_table": 9, "pos_vertical": 9},  # (4)
    "chief_geophysics": {"full": "Начальник отряда геофизики", "short": "Нач. геофизики", "type": str, "pos_table": 10, "pos_vertical": 10},  # (4)
    "chief_seismic": {"full": "Начальник отряда сейсмических исследований", "short": "Нач. сейсмики", "type": str, "pos_table": 11, "pos_vertical": 11},  # (4)
    "initiator": {"full": "Инициатор научной задачи", "short": "Инициатор", "type": str, "pos_table": 12, "pos_vertical": 12},  # (4)
    "region": {"full": "Район исследования", "short": "Район иссл.", "type": str, "pos_table": 13, "pos_vertical": 13},  # (4)
    "data_type": {"full": "Тип данных", "short": "Тип данных", "type": str, "pos_table": 14, "pos_vertical": 14},  # (4)
    "device": {"full": "Прибор", "short": "Прибор", "type": str, "pos_table": 15, "pos_vertical": 15},  # (4)
    "disk_num": {"full": "Номер диска", "short": "№ диска", "type": int, "pos_table": 16, "pos_vertical": 16},  # (4)
    "disk_inv_num": {"full": "Инвентарный номер диска", "short": "Инв. № диска", "type": int, "pos_table": 17, "pos_vertical": 17},  # (4)
    "processing_stage": {"full": "Степень обработки", "short": "Обработка", "type": str, "pos_table": 18, "pos_vertical": 18},  # (4)
    "file_format": {"full": "Формат файла", "short": "Формат", "type": str, "pos_table": 19, "pos_vertical": 19},  # (4)
    "data_volume": {"full": "Объем данных", "short": "Объем данных", "type": str, "pos_table": 20, "pos_vertical": 20}  # (4)
}                                                                                        # (0)

TABS_CONFIG = {                                                                          # (0)
    "Общая информация": ["id", "year", "cruise_name", "vessel", "cruise_num", "chief_cruise", "date_start", "date_end" ],           # (4)
    "Геофизика и приборы": ["chief_cruise", "date_start", "date_end", "stage_num"],       # (4)
    "Носители и файлы": ["chief_geophysics", "chief_seismic", "initiator", "region"],     # (4)
    "Спецификация данных": ["data_type", "device", "disk_num", "disk_inv_num"],          # (4)
    "Форматы и объемы": ["processing_stage", "file_format", "data_volume"]               # (4)
}                                                                                        # (0)

DICTIONARIES = {  # (0)
    "Судно": ["Академик Николай Страхов", "Академик Борис Петров","Академик Мстислав Келдыш", "Академик Иоффе","Академик Сергей Вавилов", "Профессор Штокман"],  # (4)
    "Начальник рейса": ["Дорохов Д.В.", "Кречик В.А.", "Крек А.В.", "Пономаренко Е.П.", "Бубнова Е.С.", "Данченков А.Р.", "Дорохова Е.В.", "Фрей Дмитрий Ильич"],  # (4)
    "Начальник отряда геофизики": [  # (4)
        "Дорохов Д.В.",  # (8)
        "Ежов В.Е.",  # (8)
        "Данченков А.Р.", # (8)
        "Дорохова Е.В.",
        "Дудков И.Ю.",
        "Кречик В.А.",
        "Пономаренко Е.П."
    ],  # (4)
    "Начальник отряда сейсмических исследований": [  # (4)
        "Ежов В.Е.",  # (8)
        "Ананьев Р.А."  # (8)
    ],  # (4)
    "Инициатор научной задачи": ["Институт океанологии", "МГУ", "РАН"],  # (4)
    "Район исследования": ["Баренцево море", "SEB", "FZ", "Балтийское море", "Атлантика"],  # (4)
    "Тип данных": ["ОЛЭ", "МЛЭ", "Профилограф", "ГЛБО", "ADCP", "SADCP", "Сейсмокоса"],  # (4)
    "Прибор": ["Konsberg EA-400", "EA-600", "SeaBat T50", "Parasound P70", "Parasound P35", "Benthos C3D", "SES2000"],  # (4)
    "Степень обработки": ["Необработанные", "Обработанные", "Сырые и обработанные"],  # (4)
    "Формат файла": ["ASD, SEG-Y", "PDS2000", "ASCII", "DTM", "GeoTiff", "SEG-Y", "RAW", "SES2000"],  # (4)
}  # (0)
